# Numerical variables. Frequency distribution table

**Background:** You are given a dataset.<br>
**Task 1:** Given that we want to divide the numbers into 6 intervals of equal width, calculate that interval width. Round up to the nearest whole number, bigger than the result that you obtain<br>
**Task 2:** Create a frequency distribution table that shows:
1. The intervals
2. The absolute frequency of each interval
3. The relative frequency of each interval

**Task 3:** Repeat task 1 and 2, but this time, use the exact interval width. Don't round up to the nearest whole number, that is.

In [1]:
import pandas as pd
import math

# Initialize the data
data = pd.DataFrame({'values': [8, 30, 30, 50, 86, 94, 102, 110, 169, 170, 176, 236, 240, 241, 242, 255, 262, 276, 279, 282]})

In [2]:
# Task 1

interval = math.ceil(((data.max() - data.min()) / 6.0).values)

print(f'The interval width is {interval}.')

The interval width is 46.

In [3]:
# Task 2

# Handle the Pandas min value return
min = data.min().values[0]

# Create empty DF
freq_table = pd.DataFrame(columns=['Interval start', 'Absolute frequency', 'Relative frequency'])

# Loop trough all intervals
for i in range(6):
    # Calculate interval
    interval_start = min + interval*i
    interval_end = min + interval*(i+1)
    interval_range = [interval_start, interval_end]

    # Calculate absolute frequency
    if i != 0:
        abs_freq = data[(data['values'] > interval_start) & (data['values'] <= interval_end)].count().values[0]
    # Handle first value
    else:
        abs_freq = data[(data['values'] >= interval_start) & (data['values'] <= interval_end)].count().values[0]
    
    # Calculate relative frequency
    rel_freq = abs_freq/len(data)

    # Add to table
    v = [interval_range, abs_freq, rel_freq]
    freq_table.loc[len(freq_table)] = v

freq_table

  Interval start  Absolute frequency  Relative frequency
0        [8, 54]                   4                0.20
1      [54, 100]                   2                0.10
2     [100, 146]                   2                0.10
3     [146, 192]                   3                0.15
4     [192, 238]                   1                0.05
5     [238, 284]                   8                0.40

In [4]:
# Task 3

# Create new un-rounded interval
new_interval = ((data.max() - data.min()) / 6.0).values

# Handle the Pandas min value return
min = data.min().values[0]

# Create empty DF
freq_table = pd.DataFrame(columns=['Interval start', 'Absolute frequency', 'Relative frequency'])

# Loop trough all intervals
for i in range(6):
    # Calculate interval
    interval_start = (min + new_interval*i)[0]
    interval_end = (min + new_interval*(i+1))[0]
    interval_range = ['%.2f' % interval_start, '%.2f' % interval_end]

    # Calculate absolute frequency
    if i != 0:
        abs_freq = data[(data['values'] > interval_start) & (data['values'] <= interval_end)].count().values[0]
    # Handle first value
    else:
        abs_freq = data[(data['values'] >= interval_start) & (data['values'] <= interval_end)].count().values[0]
    
    # Calculate relative frequency
    rel_freq = abs_freq/len(data)

    # Add to table
    v = [interval_range, abs_freq, rel_freq]
    freq_table.loc[len(freq_table)] = v

freq_table

     Interval start  Absolute frequency  Relative frequency
0     [8.00, 53.67]                   4                0.20
1    [53.67, 99.33]                   2                0.10
2   [99.33, 145.00]                   2                0.10
3  [145.00, 190.67]                   3                0.15
4  [190.67, 236.33]                   1                0.05
5  [236.33, 282.00]                   8                0.40